<html lang="en">
<link rel="stylesheet" type="text/css" href="css/zoo.css">
 <head>
  <title>Zoo Demo App</title>
  <meta charset="UTF-8" />
 </head>
 <body>

<script>

  function onGroupChange() {
    document.getElementById("table").submit();
  }

</script>

  <?php
    include "include/header.php";
  ?>

  <h3>Example 6</h3>

  <p><strong>Topic:</strong> table with sorting, filtering and paging generated by ZooTable</p>

  <p><strong>Data:</strong>'select GetGroup() as XML' and 'select GetZoo4() as XML'</p>

  <h3>The output</h3>

<?php

   include "include/ZooTable.php";
   include "include/zooXML.php";  //$definitionXML - DB access
   include "include/zooXSLT.php"; //$formatXSLT - XLST transformation

   $table = new ZooTable($definitionXML, $formatXSLT);
   echo "<fieldset style=\"height:250px;\">";
   echo "<legend>Example 6</legend>";
   echo $table->getHTML("example6.php");   
   echo "</fieldset>";

   echo "<p>The class internaly builds an XML and then tranformes it into HTML. Here is the internal XML:<p>";
   echo "<textarea rows=\"10\" cols=\"100\">";
   $xml = new SimpleXMLElement($table->getDataXML());
   $dom = new DOMDocument("1.0");
   $dom->formatOutput = true;
   $dom->preserveWhiteSpace = false;
   $dom->loadXML($xml->asXML());
   echo htmlspecialchars($dom->saveXML(), ENT_XML1);
   echo "</textarea>";

?>

 <p>The XML structure:</p>
  <ul>
    <li><strong>data</strong> - the root element</li>
    <ul>
      <li><strong>groups</strong> - data for select list (returned by list stored function)</li>
      <ul>
         <li><strong>group</strong> - definitions of select items with database @id</li>
      </ul>
      <li><strong>table</strong> - includes table components</li>
      <ul>
         <li><strong>columns</strong> - definitions of table columns (as defined in definitionXML)</li>
         <ul>
           <li><strong>entry</strong> - a column as definition</li>
           <ul>
             <li><strong>name</strong> - the name of column</li>
             <li><strong>sort</strong> - the sort char for the column</li>
           </ul>
         </ul>
         <li>custom XML returned by table stored function</li>
      </ul>
      <li><strong>buttons</strong> - the variable to format paging buttons (@count, @from, @more, @to, @prev, @next)</li>
    </ul>
  </ul>

  <h3>The code</h3>

  <p>The <strong>GetZoo4()</strong> with control arguments:</p>
  <ul>
    <li><strong>v_sort</strong> - determinates sorting order (compare 'entry/sort' in zooXML.php)</li>
    <li><strong>v_group_id</strong> - group id - the same domain as in list stored procedure (see GetGroup()).</li>
    <li><strong>v_from</strong> - the first element to be returned by SQL select (starts with 0).</li>
    <li><strong>v_offset</strong> - the number of elements to return.</li>
  </ul>
  <textarea rows="10" cols="100">
  <?php
    include "db/GetZoo4.sql";
  ?>
  </textarea>

  <p>The <strong>GetGroup()</strong> retrieves data for the select list.</p>
  <textarea rows="10" cols="100">
  <?php
    include "db/GetGroup.sql";
  ?>
  </textarea>

  <p>The <strong>ZooTable</strong> the class that renders HTML, constructor arguments:</p>
  <ul>
    <li><strong>$definitionXML</strong> - XML String - defines MySQL source of data, names of stored procedures and table columns</li>
    <li><strong>$formatXSLT</strong> - XSLT String - transformation definition</li>
  </ul>

  <textarea rows="10" cols="100">
  <?php
   $text = file_get_contents("include/ZooTable.php");
   $text = str_replace("<?php", "<--", $text);
   $text = str_replace("?>", "-->", $text);
   echo $text;
  ?>
  </textarea>

  <p>The main page using the ZooTable class</p>
  <textarea rows="10" cols="100">
  <!-- <script>
    function onGroupChange() {
       document.getElementById("table").submit();
    }
  -->

  <!-- PHP

   include "include/ZooTable.php";
   include "include/zooXML.php";  //$definitionXML - DB access
   include "include/zooXSLT.php"; //$formatXSLT - XLST transformation

   $table = new ZooTable($definitionXML, $formatXSLT);
   echo "<fieldset style=\"height:280px;\">";
   echo "<legend>Example 6</legend>";
   echo $table->getHTML("example6.php");   
   echo "</fieldset>";

  -->
  </textarea>

  <p>The <strong>zooXML.php</strong> MySQL source of data</p>
  <textarea rows="10" cols="100">
  <?php
   $text = file_get_contents("include/zooXML.php");
   $text = str_replace("<?php", "<--", $text);
   $text = str_replace("?>", "-->", $text);
   echo $text;
  ?>
  </textarea>

  <p>The <strong>zooXSLT.php</strong> - XSLT transformation, it includes 3 literals that are being replaced at runtime:</p>
  <ul>
    <li><strong>_gid_</strong> - the current group id as used for sort list and retrive table records from database</li>
    <li><strong>_sort_</strong> - the current sort value (a character) used for formatting and in call to table stored function</li>
    <li><strong>_page_</strong> - the php page that owns table, it will receive POST calls.</li>
  </ul>
  <textarea rows="10" cols="100">
  <?php
   $text = file_get_contents("include/zooXSLT.php");
   $text = str_replace("<?php", "<--", $text);
   $text = str_replace("?>", "-->", $text);
   echo $text;
  ?>
  </textarea>

  <?php
    include "include/footer.php";
  ?>


 </body>
</html>
